//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("digitalsign.application.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren.
        /// </summary>
        public static string CommonRegister {
            get {
                return ResourceManager.GetString("CommonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitloggen.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berichten.
        /// </summary>
        public static string MenuMessage {
            get {
                return ResourceManager.GetString("MenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren.
        /// </summary>
        public static string MenuRegister {
            get {
                return ResourceManager.GetString("MenuRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herinnering.
        /// </summary>
        public static string MenuReminder {
            get {
                return ResourceManager.GetString("MenuReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string MessageCreationDate {
            get {
                return ResourceManager.GetString("MessageCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniek nummer.
        /// </summary>
        public static string MessageId {
            get {
                return ResourceManager.GetString("MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw.
        /// </summary>
        public static string MessageNewLink {
            get {
                return ResourceManager.GetString("MessageNewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw Bericht.
        /// </summary>
        public static string MessageNewTitle {
            get {
                return ResourceManager.GetString("MessageNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht.
        /// </summary>
        public static string MessagePayload {
            get {
                return ResourceManager.GetString("MessagePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taak.
        /// </summary>
        public static string MessageTask {
            get {
                return ResourceManager.GetString("MessageTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn berichten.
        /// </summary>
        public static string MessageTitel {
            get {
                return ResourceManager.GetString("MessageTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string MessageUserName {
            get {
                return ResourceManager.GetString("MessageUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
    }
}
