// <auto-generated />

using digitalsign.persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace digitalsign_api.Migrations
{
    [DbContext(contextType: typeof(ApplicationDbContext))]
    [Migration("20190906213931_Message")]
    partial class Message
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Payload");

                    b.HasKey("Guid");

                    b.ToTable("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
